import { StyleSheet, Dimensions, StatusBar } from "react-native";

const { width, height } = Dimensions.get("window");

export const colors = {
  darkGreen: "#184B2C",
  midGreen: "#8FBF6F",
  cream: "#F3F7EE",
  lightGreen: "#DCEFCF",
  accent: "#BEE7A9",
  danger: "#C04A4A",
  gray: "#444",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.cream,
    padding: 16,
    paddingTop: StatusBar.currentHeight || 0,
  },
  bg: {
    flex: 1,
    width,
    height,
    resizeMode: "cover",
  },
  overlay: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  topContent: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  bottomContent: {
    alignItems: "center",
    marginBottom: 10,
  },
  welcome: {
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  subtitle: {
    color: colors.accent,
    fontSize: 20,
    marginBottom: 20,
    textAlign: "center",
  },
  brand: {
    color: colors.accent,
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.darkGreen,
    marginBottom: 16,
    textAlign: "center",
  },
  bigButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.darkGreen,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
    marginVertical: 10,
    width: "85%",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    elevation: 4,
  },
  bigButtonText: {
    color: "white",
    fontSize: 20,
    fontWeight: "600",
    marginLeft: 10,
  },
  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 10,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.midGreen,
    paddingVertical: 16,
    paddingHorizontal: 20,
    margin: 8,
    borderRadius: 12,
    flexBasis: "40%", // 2 per row
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
  },
  actionText: {
    color: "white",
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 6,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: colors.darkGreen,
    borderRadius: 10,
    padding: 12,
    marginVertical: 6,
    backgroundColor: "white",
    fontSize: 16,
  },
  primaryButton: {
    backgroundColor: colors.darkGreen,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginVertical: 12,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
  },
  secondaryButton: {
    backgroundColor: colors.lightGreen,
    borderWidth: 1,
    borderColor: colors.midGreen,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  secondaryButtonText: {
    color: colors.midGreen,
    fontWeight: "600",
    fontSize: 16,
  },
});
